### ISSUE TITLE
Edit and delete an entry, with delete confirmation modal

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/code-journal#11]
## ✅ Task List

- [x] Create edit-entry data view, and create form for editing the entry in the HTML
- [x] Add an edit/delete button to the DOM tree that is rendered for each new entry
- [x] Add a delete button to the edit-entry data view
- [x] Create a delete entry modal to confirm deleting the entry, which opens when the delete button is clicked
- [x] Auto-fill edit-entry page with existing entry data
- [x] Update entry data when edit-entry form is submitted
- [x] Remove entry from entries view/data object when delete confirmation button is clicked
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
- [x] Fix bugs
