### ISSUE TITLE
Search Entries

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/code-journal#13]
## ✅ Task List

- [x] Add a form with a "search" input field and submit button to the entries view HTML, just above the first entry.
- [x] Add an "X" to the HTML next to the search form for exiting the search
- [x] Add a 'submit' event listener for the search form. In the callback function:
   - [x] Loop through the `data.entries` array and find find search matches in `title` and `notes` properties using the .includes() method.
   - [x] Call `dataViewSwap('entries')`
- [x] Edit `dataViewSwap()` definition to include if statement determining whether a search has been executed.
   - [x] If it has, render `entries` view with only entries matching search terms
- [x] Add a 'click' event listener on the "X". In the callback function:
   - [x] reset() the search form.
   - [x] Call `dataViewSwap('entries')`
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again and fix bugs.
