### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/code-journal#15]
## ✅ Task List

- [x] Add a button in the footer to "Toggle Dark Mode On/Off"
- [x] Create a "dark-mode" class to apply to body element to change background color, text color, form input backgrounds, and anything else necessary to give the page a dark theme
- [x] Add "dark-mode" property to data model with boolean false
- [x] Add event listener to "Toggle" button, and in the function:
   - [x] Reference data model to determine dark mode status
   - [x] Apply necessary classes
   - [x] Invert data model boolean
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
